export { isPrimitive } from './isPrimitive.js'
export { hasChild } from './hasChild.js'
export { isNullish } from './isNulllish.js'
export { isIterable } from './isIterable.js'
export { isFunction } from './constructorName.js'